export const NOTES = {
    ACTION_UPDATE_NOTES_STORE: 'ACTION_UPDATE_NOTES_STORE',
    ACTION_UPDATE_NOTE_BY_ID: 'ACTION_UPDATE_NOTE_BY_ID',
    ACTION_DELETE_NOTE_BY_ID: 'ACTION_DELETE_NOTE_BY_ID',
    ACTION_CLEAR_NOTES_STORE: 'ACTION_CLEAR_NOTES_STORE',
    EPIC_FETCH_NOTES_BY_USER_ID: 'EPIC_FETCH_NOTES_BY_USER_ID',
    EPIC_CREATE_NOTE: 'EPIC_CREATE_NOTE',
    EPIC_UPDATE_NOTE_BY_ID: 'EPIC_UPDATE_NOTE_BY_ID',
    EPIC_DELETE_NOTE_BY_ID: 'EPIC_DELETE_NOTE_BY_ID',
    
}

export const USER = {
    ACTION_UPDATE_USER_STORE: 'ACTION_UPDATE_USER_STORE',
    ACTION_CLEAR_USER_STORE:  'ACTION_CLEAR_USER_STORE',
    EPIC_FETCH_USER_DATA: 'EPIC_FETCH_USER_DATA'
}

export const GENERAL = {
    EPIC_CLEAR_STORE: 'EPIC_CLEAR_STORE'
}